name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to release from
        required: true
        default: ''

permissions:
  contents: write

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag }}
          target_commitish: ${{ github.sha }}
          name: Release ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
