name: Update AL-Go System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is https://github.com/microsoft/AL-Go@main)
        required: false
        default: ''
      directCommit:
        description: Direct Commit (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write
  actions: read

defaults:
  run:
    shell: powershell

jobs:
  UpdateALGoSystemFiles:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v9.0
        with:
          shell: powershell

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v9.0
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v9.0
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Update AL-Go System Files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@v9.0
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          templateUrl: ${{ github.event.inputs.templateUrl }}
          downloadLatest: 'true'
          directCommit: ${{ github.event.inputs.directCommit }}
          update: 'Y'

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v9.0
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
